# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servo', '0027_remove_location_logo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attachment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='checklist',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='device',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='event',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='flaggeditem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='note',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='productcategory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='queue',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='rateditem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='taggeditem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='timeditem',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='site',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='site',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='site',
        ),
        migrations.RemoveField(
            model_name='device',
            name='site',
        ),
        migrations.RemoveField(
            model_name='event',
            name='site',
        ),
        migrations.RemoveField(
            model_name='flaggeditem',
            name='site',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='site',
        ),
        migrations.RemoveField(
            model_name='note',
            name='site',
        ),
        migrations.RemoveField(
            model_name='order',
            name='site',
        ),
        migrations.RemoveField(
            model_name='product',
            name='site',
        ),
        migrations.RemoveField(
            model_name='property',
            name='site',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='site',
        ),
        migrations.RemoveField(
            model_name='rateditem',
            name='site',
        ),
        migrations.RemoveField(
            model_name='search',
            name='site',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='site',
        ),
        migrations.RemoveField(
            model_name='taggeditem',
            name='site',
        ),
        migrations.RemoveField(
            model_name='template',
            name='site',
        ),
        migrations.RemoveField(
            model_name='timeditem',
            name='site',
        ),
        migrations.RemoveField(
            model_name='user',
            name='site',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='site',
        ),
        migrations.AlterField(
            model_name='queue',
            name='title',
            field=models.CharField(default='New Queue', unique=True, max_length=255, verbose_name='Title'),
        ),
    ]
