# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:26
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('servo', '0046_auto_20160209_1458'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='repair',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
