# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servo', '0047_auto_20160225_2326'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='repair',
            managers=[
            ],
        ),
    ]
