# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 14:34
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servo', '0049_gsxaccount_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsx_id', models.CharField(default=b'', editable=False, max_length=20)),
                ('date_created', models.DateField(editable=False)),
                ('date_published', models.DateField(null=True)),
                ('title', models.TextField(default='New Article')),
                ('summary', models.TextField(default=b'')),
                ('content', models.TextField(default=b'')),
                ('priority', models.CharField(choices=[(b'HIGH', 'High'), (b'MEDIUM', 'Medium'), (b'LOW', 'Low')], default=b'HIGH', max_length=128)),
                ('url', models.URLField(default=b'')),
                ('product_model', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), editable=False, null=True, size=None)),
                ('read_by', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('flagged_by', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='serviceorderitem',
            name='comptia_code',
            field=models.CharField(blank=True, default=b'', max_length=4, verbose_name='Symptom code'),
        ),
        migrations.AlterField(
            model_name='serviceorderitem',
            name='comptia_modifier',
            field=models.CharField(blank=True, default=b'', max_length=1, verbose_name='Symptom modifier'),
        ),
    ]
