# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 14:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servo', '0050_auto_20160229_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdevice',
            name='repair_strategies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), help_text=b'Available repair strategies from GSX', null=True, size=None),
        ),
        migrations.AddField(
            model_name='orderdevice',
            name='repeat_service',
            field=models.BooleanField(default=False),
        ),
    ]
