# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servo', '0053_auto_20160321_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='flagged_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
